---
title: "Introduction"
subtitle: "*NJ Gr&uuml;nwald and ZSL Foster*"
bibliography: "bibtexlib.bib"
---

```{r,message=FALSE,echo=FALSE}
library("knitcitations")
cleanbib()
bib <- read.bibtex("bibtexlib.bib")
library("knitr")
cite_options(citation_format = "pandoc", max.names = 3, style = "html", hyperlink = "to.doc")
opts_chunk$set(tidy = FALSE, message = FALSE, warning = FALSE)
```

## What we will cover

This primer provides a concise introduction to conducting the statistical analyses and visualize microbiome data in R based on metabarcoding and high throughput sequencing (HTS). 
This primer does not cover "shotgun" metagenomic analysis, which is very different in nature.
The reader is expected to have a very basic understanding of ecological diversity theory and some experience with R. 
The techniques presented here assume the exact sequence variants (ESVs) or operational taxonomic units (OTUs) have already been called and classified (i.e., assigned a taxonomy) using tools such as QIIME or mothur [@schloss2009introducing; @caporaso2010qiime]. 

## Why use R?

R is an open source (free) statistical programming and graphing language that includes
tools for analysis of statistical, ecological diversity and community data, among many other things.
R provides a cohesive environment to analyze data using modular "toolboxes" called R **packages**.
R runs on all major operating systems including Microsoft Windows, Linux (e.g., Ubuntu), and Apple's OS X.
The general type of analyses done in this workshop could be done in python, Perl, or using command line tools.
We like R for the following reasons:

* We use it (i.e., we are biased).
* R packages are easy to install and not too hard to make.
* The R community is very active and growing. Packages are updated frequently.
* Repositories such as CRAN and Bioconductor provide some quality control of packages and make them easy to install.
* RStudio is a great, free graphics user interface.
* R Markdown is well supported, allowing R code to be embedded in documents and output to diverse formats. This website is the output of a set of R Markdown documents. Thus, R markdown can be used as an electronic notebook facilitating for reproducible research [link](http://grunwaldlab.github.io/Reproducible-science-in-R/). 
* R has strong graphing and statistical capabilities. 
* You can produce publication ready graphics 
* R is designed to be an interactive language, providing a natural fit for statistical analyses rather than writing programs.

## The kind of data used in this workshop

This workshop will not start with the raw reads, since the first steps in a metabarcoding workflow are typically done using command line tools such as QIIME or mothur (dada2 is an exception) in the cloud.
Data that can be analysed using techniques presented here is typically the result of the following steps [@comeau2017microbiome]:

1. Sample environments/soil/tissue/water and extract DNA.
1. Perform PCR using standard primers.
1. Sequence using a high-throughput sequencing platform such as the Illumina MiSeq.
1. Call OTUs/ESVs and assign a taxonomic classification by comparing them to a reference database, such as Greengenes.
1. Construct an abundance matrix of read counts for each OTU in each sample.

Here we focus on the statistical analysis and visualizations following OTU calling that include:

- Reading files into R
- Manipulating tabular and taxonomic data
- Heat trees [@foster2017metacoder], stacked bar charts and related visualizations
- Alpha and beta diversity
- Ordination methods

## Help us improve this resource

We hope you enjoy this primer. 
Please let us know if a section is critically missing or has bugs. 
We will continue to improve this resource.

References
----------

<!---- Reference list ---->
